version: '1.0'

services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "33306:3306"
    environment:
      MYSQL_DATABASE: api_supermarket
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_PASSWORD: 123123
  
  api:
    build: .
    container_name: api
    ports:
      - "9000:9000"
    depends_on:
      - db
    restart: on-failure